---

- name: Setup php7.0-fpm pool configuration
  template:
    src: 'etc/php/7.0/fpm/pool-available.d/pool.conf.j2'
    dest: '/etc/php/7.0/fpm/pool-available.d/{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: php7_pools
  notify: [ 'Reload php7.0-fpm' ]

- name: Enable php7.0-fpm pools
  file:
    path: '/etc/php/7.0/fpm/pool.d/{{ item.name }}.conf'
    src: '/etc/php/7.0/fpm/pool-available.d/{{ item.name }}.conf'
    state: 'link'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: php7_pools
  when: item.enabled is not defined or item.enabled == True
  notify: [ 'Restart php7.0-fpm' ]

- name: Disable php7.0-fpm pools
  file:
    path: '/etc/php/7.0/fpm/pool.d/{{ item.name }}.conf'
    state: 'absent'
  with_items: php7_pools
  when: item.enabled is defined and item.enabled == False
  notify: [ 'Restart php7.0-fpm' ]
